apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchangerates-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: exchangerates-app
spec:
  project: default
  source:
    repoURL: https://github.com/mayur0601/exchangerates.git
    targetRevision: main
    path: k8chart
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - pruneLast=true
